### ISSUE TITLE
Curious why I cant run your code on an emulator

### ISSUE THREAD

**Issue by Isonomic** [seenickcode/tourismandco#1]
This is the error I get

Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:62771/ydhO9Obo93M=/ws

**Comment by dodiameer** [comment]
You're trying to connect to localhost, in this case it's the device's own loopback system not your computer's. In Android emulator, you can use the address 10.0.2.2 instead, which will be localhost of your own computer.

**Comment by seenickcode** [comment]
I've updated the repo to work with the latest null safety and a min Flutter version of 2.12

If you have a general issue outside of this repo, please email nick@fluttercrashcourse.com thanks
