### ISSUE TITLE
Help with Button Creation

### ISSUE THREAD

**Issue by ramandeepqa** [seenickcode/tourismandco#3]
Hello Nick,

I am trying to complete stepX where we add red button on the location_detail page. I am able to add the button using floatingActionButton but it is not accepting box decoration. Can you please review and let me know if I'm doing something wrong.

https://github.com/ramandeepqa/tourism/blob/master/lib/screens/location_details/location_detail.dart

**Comment by seenickcode** [comment]
I've updated the repo to work with the latest null safety and a min Flutter version of 2.12
