### ISSUE TITLE
STEP06 settings.arguments & fetchByID

### ISSUE THREAD

**Issue by mahmoud-bebars** [seenickcode/tourismandco#4]
settings.arguments is not working 
`final Map<String, dynamic> arguments = settings.arguments;`
and through this error :

-> A value of type 'Object?' can't be assigned to a variable of type 'Map<String, dynamic>'.
Try changing the type of the variable, or casting the right-hand type to 'Map<String, dynamic>'

& the fetchByID is having also an error because of the `return null;`

 ```
static Location fetchByID(int locationID) {
    // NOTE: this will replaced by a proper API call
    List<Location> locations = Location.fetchAll();
    for (var i = 0; i < locations.length; i++) {
      if (locations[i].id == locationID) {
        return locations[i];
      }
    }
    return null;
  }
```

---> A value of type 'Null' can't be returned from the method 'fetchByID' because it has a return type of 'Location'.

**Comment by yong-soong** [comment]
same error here, please help

**Comment by seenickcode** [comment]
Hi there @mahmoud-bebars my apologies for replying so late here. I've updated the repo to work with the latest null safety and a min Flutter version of 2.12

**Comment by c151423m** [comment]
Hi @seenickcode , 

Can you point us how you fixed the below part in the app.dart ?

`final Map<String, dynamic> arguments = settings.arguments;
`
With the latest flutter version, as @mahmoud-bebars mentioned, it returns the error as below . 

```
-> A value of type 'Object?' can't be assigned to a variable of type 'Map<String, dynamic>'.
Try changing the type of the variable, or casting the right-hand type to 'Map<String, dynamic>'
```

The workaround I came up was to revert the version to pre null safety ( ie match to the version you used in the video ) but wanted to know if there's a way to fix this in the current version .
